version: '3.8'

services:

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/data:/data
      - ./backend/config.yaml:/config.yaml
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery

  celery:
    build:
      context: ./backend
    command: celery --app=src.main.celery_app worker --concurrency=1 --loglevel=info
    volumes:
      - ./backend/data:/data
      - ./backend/config.yaml:/config.yaml
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
