refresh_period_seconds: 15
services:

    # * this example check should should be green
  - url: https://www.w3schools.com/
    expected_status_code: 200
    xpath: "//*[contains(text(), 'Log in')]"    # use xpath parameter to check if specific contect exists on a page

    # * this one should be yellow
  - url: https://github.com/
    expected_status_code: 200
    xpath: "//*[contains(text(), 'some dummy string that is not on the page')]"

    # * red
  - url: https://nonExistingDomainForReal.com/
    expected_status_code: 200

    # * red - should return 404 instead of 200
  - url: https://jsonplaceholder.typicode.com/posts/2137
    expected_status_code: 200

    # * green
  - url: https://jsonplaceholder.typicode.com/posts/1
    expected_status_code: 200

    # * red - should return 200 instead of 404
  - url: https://jsonplaceholder.typicode.com/posts/1
    expected_status_code: 404
